package DBSApp;


/**
* DBSApp/DBSInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DBSInterface.idl
* Friday, November 30, 2007 12:32:09 o'clock AM EST
*/

public interface DBSInterfaceOperations 
{
  float deposit (int acnt, float amt);
  float withdraw (int acnt, float amt);
  float balance (int acnt);
  float transfer (int src_acnt, int dest_acnt, float amt);
} // interface DBSInterfaceOperations
