package DBSApp;


/**
* DBSApp/DBSInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DBSInterface.idl
* Friday, November 30, 2007 12:32:08 o'clock AM EST
*/

public abstract class DBSInterfacePOA extends org.omg.PortableServer.Servant
 implements DBSApp.DBSInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("deposit", new java.lang.Integer (0));
    _methods.put ("withdraw", new java.lang.Integer (1));
    _methods.put ("balance", new java.lang.Integer (2));
    _methods.put ("transfer", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DBSApp/DBSInterface/deposit
       {
         int acnt = in.read_long ();
         float amt = in.read_float ();
         float $result = (float)0;
         $result = this.deposit (acnt, amt);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 1:  // DBSApp/DBSInterface/withdraw
       {
         int acnt = in.read_long ();
         float amt = in.read_float ();
         float $result = (float)0;
         $result = this.withdraw (acnt, amt);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 2:  // DBSApp/DBSInterface/balance
       {
         int acnt = in.read_long ();
         float $result = (float)0;
         $result = this.balance (acnt);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // DBSApp/DBSInterface/transfer
       {
         int src_acnt = in.read_long ();
         int dest_acnt = in.read_long ();
         float amt = in.read_float ();
         float $result = (float)0;
         $result = this.transfer (src_acnt, dest_acnt, amt);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DBSApp/DBSInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DBSInterface _this() 
  {
    return DBSInterfaceHelper.narrow(
    super._this_object());
  }

  public DBSInterface _this(org.omg.CORBA.ORB orb) 
  {
    return DBSInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class DBSInterfacePOA
