package DBSApp;


/**
* DBSApp/DBSInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DBSInterface.idl
* Friday, November 30, 2007 12:32:09 o'clock AM EST
*/

abstract public class DBSInterfaceHelper
{
  private static String  _id = "IDL:DBSApp/DBSInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, DBSApp.DBSInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DBSApp.DBSInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DBSApp.DBSInterfaceHelper.id (), "DBSInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DBSApp.DBSInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DBSInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DBSApp.DBSInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DBSApp.DBSInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DBSApp.DBSInterface)
      return (DBSApp.DBSInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DBSApp._DBSInterfaceStub stub = new DBSApp._DBSInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DBSApp.DBSInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DBSApp.DBSInterface)
      return (DBSApp.DBSInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DBSApp._DBSInterfaceStub stub = new DBSApp._DBSInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
