package DBSApp;


/**
* DBSApp/DBSInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DBSInterface.idl
* Friday, November 30, 2007 12:32:09 o'clock AM EST
*/

public interface DBSInterface extends DBSInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DBSInterface
