package DBSApp;

/**
* DBSApp/DBSInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DBSInterface.idl
* Friday, November 30, 2007 12:32:09 o'clock AM EST
*/

public final class DBSInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public DBSApp.DBSInterface value = null;

  public DBSInterfaceHolder ()
  {
  }

  public DBSInterfaceHolder (DBSApp.DBSInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DBSApp.DBSInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DBSApp.DBSInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DBSApp.DBSInterfaceHelper.type ();
  }

}
